### ISSUE TITLE
Allow failing of steps based on return value, not just caught exceptions

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-transaction#1]
Right now, using a `try` step and catching an exception is the only straightforward way to fail a transaction. However, exceptions won't always be available, nor always desirable, as an indicator of an operation's failure.

I added the "inline procs" example to the README as a way to fail a transaction based on the result of the previous operation, but it's not very nice, and may perhaps encourage too much custom logic to go into the transaction object (when all of that logic should really reside purely in the operations).

I'd like to offer a slightly more declarative way of failing a step based on its return value.

Maybe something like this:

``` ruby
save_user = CallSheet(container: container) do
  # send `:locked?` to the output of the `find_user` operation and failed the step if t's truthy
  map :find_user, fail_if: :locked?
end
```

With support for this too:

``` ruby
save_user = CallSheet(container: container) do
  # fail the operation if the proc returns something truthy
  map :find_user, fail_if: -> output { output.created_at < Time.local(2014,1,1) }
end
```

If we went for an approach like this, we'd want to offer the `fail_if:` option on both the `map` and `try` steps.

**Comment by timriley** [comment]
We could also add `fail_unless:` to match Ruby's two if/unless flow control options.

**Comment by solnic** [comment]
@timriley to be honest I don't think it's a good idea and it's one of the reasons why I didn't add any "conditionals" as options to the DSL in transflow and used Either from kleisli, it's so much cleaner to do it like that. I want the transaction DSL to be clean, focusing on the flow rather than details like conditional logic. It boils down to using monads as values and relying on that interface rather than some complicated DSL setup.

**Comment by timriley** [comment]
@solnic Yes, I think you're right. In fact, I think it might be nice to provide an alias for `raw` called `step` so you could have a more natural word to build up a series of steps that are _already_ returning result monads in Call Sheet. 

However, the tricky thing is that I'd also like Call Sheet to be usable for people who _don't_ have monads as return values all across their application's operations. That's the reasoning behind the step adapters, to provide some way to build a mostly declarative flow of steps, even if those steps aren't quite perfectly suited to being chained together in the first place. I think this would help Call Sheet be a usable option in a greater number of circumstances, which is probably a net win. 

So they're the two sides of the issue. I hear you about the risk of conditional logic complicating the transaction, but I see its benefits in certain cases too. Can you thin of any other ways we might be able to serve both purposes nicely?

**Comment by solnic** [comment]
I think number 1 priority is to keep the flow DSL clean and logic-less free. You could introduce a concept of a step that's only purpose is to make a decision whether another step should be executed or an error should be raised. Maybe it should be called "a contract step"? Something like:

``` ruby
map :find_user, contract: :verify_user
```

This way people could keep their existing logic, theoretically :)

**Comment by timriley** [comment]
You've convinced me, @solnic. Even if the rest of the operations don't Result monads, it's easy enough to add extra steps to make verification checks on the value an return Success/Failure objects as necessary. I don't even think we need a special `contract:` option here, since they work just as well as top-level steps like everything else.

I've also removed the feature of supporting procs passed to the step `with:` option, so now there's no facility whatsoever to inject custom logic into the transaction object. Everything must be in a step!

**Comment by solnic** [comment]
@timriley sounds good! :)
