### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by anthony-bernardo** [dry-rb/dry-transaction#100]
How to inject an object (like a repository) in a transaction ?
I want to do this, for unit testing the transaction

**Comment by timriley** [comment]
@xero88 GitHub issues aren't for support requests. Please make your request (and include some sample code) on https://discourse.dry-rb.org.

**Comment by anthony-bernardo** [comment]
Yes I posted in the forum. But for now no responses.
But can you confirm that this functionality is implemented or not ?

**Comment by timriley** [comment]
@xero88 See my reply here: https://discourse.dry-rb.org/t/dry-transaction-injection/528/5?u=timriley. Please carry on future correspondence in the forum.
