### ISSUE TITLE
Improve error when returning a bad object in step

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-transaction#11]
If I define a step and forget to return an `Either` object the error is quite cryptic: "NoMethodError: undefined method `fmap' for nil:NilClass" It would be nice if this showed another error indicating that the expectation was broken.

**Comment by timriley** [comment]
@davidpelaez This is a great idea, thanks! I'll look at incorporating this the next time I'm working on call_sheet :)

**Comment by davidpelaez** [comment]
Just sent a small PR to add this error. I had the problem and it was confusing to figure out where it came from so this looks useful to better assist the "type safe" style being recently promoted in functional ruby things like Dry-types :)
