### ISSUE TITLE
Best way to pass new parameters to the next step

### ISSUE THREAD

**Issue by cmavromoustakos** [dry-rb/dry-transaction#116]
I have a scenario where a transaction calls another transaction (which I am reusing elsewhere) and adds a parameter from the result of that transaction to the call to the next step. The code is as follows:

```
 ┆ def validate_attributes(gig:, indie:)
 ┆ ┆ Operations::ValidateGig.new.call(gig: gig).bind do |result_value|
       gig = result_value.fetch(:gig)
 ┆ ┆ ┆ Success(gig: gig, indie: indie)
 ┆ ┆ end
 ┆ end
```

Is there a more elegant way that is recommended to accomplish the above? My worry is that I am using the library in a way that is not documented and this could possibly break in future versions.

**Comment by timriley** [comment]
Hi Constantine, could you please move this question to http://discourse.dry-rb.org? We don’t use Github issues for support questions.

Appreciate it!

Tim
