### ISSUE TITLE
A larger container with 'with' option expects larger key instead of nested hash 

### ISSUE THREAD

**Issue by blelump** [dry-rb/dry-transaction#13]
Hi @timriley  , 

I'm playing with call_sheet (or dry-transaction – not sure where to open issues) and found that when using `with` option, it looks for a long key (e.g `persistance.commands.update_user`) whereas I'd expect it works like below:

```
{
  persistance: {
    commands: {
      update_user: -> {}
    }
}

# vs:

{
  'persistance.commands.update_user': -> {}
}
```

Wouldn't it be easier to read? What do you think?
#### Update:

Nevermind, `dry-container` does the job!

**Comment by timriley** [comment]
@blelump Glad you found what you needed :) Yeah, the dotted syntax is really there to demonstrate dry-container namespaces, not any sort of nested hash structure. I think it might be worth adjusting the README to just use dry-container from the beginning.
