### ISSUE TITLE
Bump dry-matcher to 1.0

### ISSUE THREAD

**Issue by santiagodoldan** [dry-rb/dry-transaction#148]
## Describe the bug

dry-matcher released version 1.0 and current gemspec is causing conflicts to bump it.

## Expected behavior

being able to install dry-matcher 1.0

If the project is still active 🤞  I'm available to open a PR 💯

**Comment by timriley** [comment]
Feel free to make a PR, then I'll cut a release.

**Comment by santiagodoldan** [comment]
@timriley Created the PR -> https://github.com/dry-rb/dry-transaction/pull/149, I was not sure about touching gemspec file, let me know if I have to revert that change, thanks 🙌

**Comment by santiagodoldan** [comment]
@timriley thank you for merging the PR, feel free to close the issue when releasing a new version 💯

**Comment by santiagodoldan** [comment]
@timriley hey, is there anything missing to release a new version? let me know if there is anything I can help you with 🙌

**Comment by santiagodoldan** [comment]
@timriley sorry to ping you again, it would be awesome to get the new version as this is preventing dependabot updating other gems

**Comment by timriley** [comment]
@santiagodoldan I've just released 0.16.0, with the dependency on dry-matcher 1.0.
