### ISSUE TITLE
README missing some key infos for newbies / curious visitors

### ISSUE THREAD

**Issue by jmgarnier** [dry-rb/dry-transaction#21]
This is a question about marketing of your `dry-transaction` project. Would it better to discuss straight on https://gitter.im/dry-rb/chat ?

The previous name (`callsheet`) and the current name do not give much clue about the features. Since commit https://github.com/dry-rb/dry-transaction/commit/736451ca01d12b35e51778c79f07b80260e5f499 , most of the README is empty and you have to click on the "Documentation" and then "Basic usage" to see some code. 

May I recommend you to duplicate some of the documentation and keep some key selling points with some code sample to explain what the gem does? As a ruby developer, I am so used to compare gems by comparing READMEs (and then looking at tests, downloads, documentation) that I am a bit surprised by a short README.

Judging by the [growing popularity](https://pinboard.in/u:jmg/t:ruby/t:service) of such libraries, I have the felling your library desserves more attention as it has some unique features (railway oriented programming)

**Comment by timriley** [comment]
Thanks for your thoughts, @jmgarnier, but for the dry-rb projects, we're opting to keep the READMEs small and link out to the website, where we'll be keeping all our docs and other introductory material :)
