### ISSUE TITLE
Share example of how a business transaction could be wrapped in a database transaction

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-transaction#29]
This seems like it would be an important thing to support/demonstrate for certain types of uses.

**Comment by flash-gordon** [comment]
@timriley I have a sample btw https://gist.github.com/flash-gordon/64ebb082ec2a253db3a727bd7eafc393#file-transaction-example-rb-L2-L25 
Haven't tried to use it with pub/sub yet though it's on my schedule

**Comment by timriley** [comment]
@flash-gordon that's neat! Thanks for sharing 😄 

I've been thinking about database transactions and have been wondering whether we should support some sort of user-provided "around" operation that can wrap each of the steps in the transaction. The goal would be to make it more straightforward to achieve what you have done with your `TransactionWrapper`. What do you think?

**Comment by flash-gordon** [comment]
I think we need to start with some wishful thinking of desired interface. It can be

``` ruby
Dry.Transaction(:container, wrap_with: suting_responding_to_call)
```

or

``` ruby
Dry.Transaction.register_wrapper(:db_transaction, Wrapper.new)
Dry.Transaction(:container) do
  step :pure_one
  step :pure_two
  wrap :db_transaction do
    # persisting
    step :dirty_three
  end
end
```

**Comment by solnic** [comment]
Not sure if I like this, why not just wrap it yourself in your object?

**Comment by flash-gordon** [comment]
@solnic it's more about best practices. I know for sure people underestimate importance of DB transaction especially when the are well supported by the database (e.g. in PG). No matter which option we choose we must describe how to handle DB transactions properly. Look at my example, I use exceptions for flow control which is definitely is not what I would recommend to do at home, I'm really curious if there is a better way. At least I don't want people to reimplement this solution if it is possible.

**Comment by pabloh** [comment]
Is there, right now, a recommended way to achieve this?

**Comment by thil** [comment]
We are looking into this issue as well, not sure what the plan is to tackle this ? But we extended it so that you can have nested steps,

```
  step :process
  step :with_db_transaction do
    step :persist_a
    step :persist_b
  end
```

This then enables us to wrap the nested transactions within the `with_db_transaction` method.  This also gives the added benefit of wrapping steps which means that if you wanted to exit the dry transaction early you can.

**Comment by timriley** [comment]
@thil We actually just merged support for "around" steps to handle this: https://github.com/dry-rb/dry-transaction/pull/85

**Comment by thil** [comment]
@timriley Thanks that looks awesome, but is `around` keyword a bit misleading, as its not actually `around`.

**Comment by flash-gordon** [comment]
@thil what do you mean by that? A step defined as `around` will be called "around" indeed :) As in, it wraps all the following steps by yielding a block. I didn't try but it should even be able to short circuit the execution of a transaction (although, don't see why at this point).

**Comment by thil** [comment]
I guess for me when I look at `around` I think around what, looking at that its not really explicit where its around to.  Maybe I am being nitpicky.  I was thinking it would be nice to have it like `wrap` is done in Trailblazer.

As for short circuit an example we use it is with applying coupons.  The user can apply a coupon, but it is not required to be entered, but we don't want to fail the use_case if its not entered.  So short circuit and return `Right` if it has not been entered otherwise continue along the use case.  So yes that would work with this solution.  

@flash-gordon Thanks for adding this feature.

**Comment by solnic** [comment]
> I guess for me when I look at around I think around what, looking at that its not really explicit where its around to.

I agree. It looks very strange right now.

**Comment by joelvh** [comment]
Hi all, i'm just getting going using the Dry gems and looking forward to leveraging what you guys have put a great effort into.

I'm intending to use transactions as steps within other transactions as a means of composition, which I presume is what dry-transaction is designed for. I was going to suggest that maybe there's a way to use a block with the `around` step by building a transaction on which the nested steps are added.

I was starting to get confused about if/how that might be possible and it seems that the API docs are outdated (v0.5.0 - http://www.rubydoc.info/github/dry-rb/dry-transaction/Dry/Transaction). The old docs imply that you can build a transaction with a block, which would have worked perfectly with this `around` use case. However, it seems that the API has changed, but maybe a nested transaction is still an option to solve for making this DSL more intuitive?

Just my 2¢

Also, are nested transactions an intended use case - or is there a different way to compose steps? Anything to look out for as I go down that route?

Thanks!

**Comment by timriley** [comment]
We have http://dry-rb.org/gems/dry-transaction/around-steps/ now.

**Comment by mengqing** [comment]
Really loving this feature, this is awesome.

I've got a few questions in regards to transaction and I'm hoping to get some advices

1. Looking at the example, I'm assuming that when you place an `around` step, using the DB transaction as an example, that means that all the subsequent steps in that operation would be wrapped in a transaction. Would it be possible though, to specify which steps I need to wrap around, and not all the steps? What would be the recommended approach to solve this issue?

2. If I need a different rollback strategy on each of the steps in the operation, how would I do that?

**Comment by EugZol** [comment]
Any updates on @mengqing's questions?
