### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by pascalbetz** [dry-rb/dry-transaction#32]
Trying out dry-transactions and found that the samples are not working out of the box. Probably not updated when some changes were made in regards to `dry-monads`?
Here is a working sample:

```
require 'dry-transaction'
require "dry-container"
require 'dry-monads'    # added this
# require 'kleisli'           # removed this
include Dry::Monads   # added this
DB = []

class Container
  extend Dry::Container::Mixin

  register :process, -> input { Right(name: input["name"], email: input["email"]) }
  register :validate, -> allowed, input { input[:email].include?(allowed) ? Left(:not_valid) : Right(input) }
  register :persist, -> input { DB << input; Right(:input) }
end

save_user = Dry.Transaction(container: Container) do
  step :process
  step :validate
  step :persist
end

input = {"name" => "Jane", "email" => "jane@doe.com"}
save_user.call(input, validate: ["doe.com"])
# => Right({:name=>"Jane", :email=>"jane@doe.com"})

save_user.call(input, validate: ["smith.com"])
# => Left(:not_valid)

```

**Comment by timriley** [comment]
@pascalbetz Ah yes, I think you're being bitten by the fact that kleisli installs a global monkey patch for `Left` and `Right`, but dry-monads does not.

You have two options:
1. Inside Container, `extend Dry::Monads::Either::Mixin` and then things should work, or
2. Just call `Dry::Monads.Right` directly in your steps, instead of `Right`

**Comment by timriley** [comment]
I'll actually leave this open as a reminder to update the docs.

**Comment by timriley** [comment]
Docs are updated now!

**Comment by pascalbetz** [comment]
Hello @timriley 

thanks for the update. I prefer explixitely using `Driy::Monads::Right|Left` instead of including. So i went that way.

Pascal
