### ISSUE TITLE
Feature request: prepend operation arguments from the DSL block

### ISSUE THREAD

**Issue by rewritten** [dry-rb/dry-transaction#37]
It would be useful to be able to natively pass through all the unrecognized options from the transaction block as additional kwargs at execution time. 

I see a clear use case of that when having a generic configurable step and building a transaction with a specific configurable instance of it. The configurability is large enough so it does not make much sense to have several separate steps in the container, and on the other side, the specific configured options are not a concern of the caller of the transaction, so it seems that it really is something to be in the DSL. 

Example:

```
transaction do
  step :something_that_returns_an_object
  step :wrap_in_hash with_key: :thing
  step :something_that_takes_a_hash
end
```

The actual hash key in this case is more like glue code, and for reusability it would be awesome not to have to create too many different steps. 

I understand that it could be encoded as a different step adapter, but then one would lose all the good stuff about managing Either and exceptions (using raw/try/tee). 

**edit**

After thinking about it, it might be useful (even if all the examples I have in mind can be done with custom step adapters etc) to have a way to prepend arguments not just at the time of calling the transaction, but at the time of definition:

``` ruby
container = {
  process:  -> input { {name: input["name"], email: input["email"]} },
  validate: -> allowed, input { input[:email].include?(allowed) ? raise(ValidationFailure, "not allowed") : input },
  persist:  -> db, input { db << input and true }
}

save_user = Dry.Transaction(container: container) do
  map :process
  try :validate, catch: ValidationFailure
  tee :persist, args: [DB]
end

input = {"name" => "Jane", "email" => "jane@doe.com"}
save_user.call(input, validate: ["doe.com"])
```

the actual arguments to each operation would be

```
args = call_args + @options[:args] + [input]
```

This will allow to underspecify operations in the container, but still make the completely specified at definition time.

**Comment by timriley** [comment]
@rewritten I reckon this should all be doable for you now that we have class-based transactions (see the latest release) and all the normal flexibility that Ruby gives you with regular class design? I'm going to close this accordingly but please do let me know if you see any issues still.
