### ISSUE TITLE
Change signature of call methods for accepting extra step arguments

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-transaction#39]
The current signature:

```
def call(*args, input)
```

Is kind of awkward, especially for optional extra arguments.

It'd be better to make it:

```
def (input, *args)
```

**Comment by mrbongiolo** [comment]
@timriley are you referring to the `operation.call()` within the step adapter, or am I confusing something?

**Comment by timriley** [comment]
This is fixed by #48 :)
