### ISSUE TITLE
Allow to override StepAdapters

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-transaction#46]
Could we change the StepAdapters container `registry` configuration to allow for overriding instead of the default behavior of just raising an issue if trying to define a step_adapter with the same name.

I had to modify the `Try` step adapter, and in order to do so I end up having to rewrite all basic step adapters inside my CustomStepAdapters module.

What do you think @timriley?

**Comment by timriley** [comment]
@mrbongiolo how do you mean rewrite? Do you actually just mean this?

``` ruby
class MyAdapters
  extend Dry::Container::Mixin

  register :map, Dry::Transaction::StepAdapters::Map.new
  register :tee, Dry::Transaction::StepAdapters::Tee.new
  register :try, MyTry.new
  register :step, Dry::Transaction::StepAdapters::Raw.new
end
```

Or something else?

**Comment by mrbongiolo** [comment]
Ops! That's it @timriley. nvm I just forgot that I could register the step adapters directly from Dry::Transaction, my bad. :facepalm:
