### ISSUE TITLE
Compose transactions

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dry-rb/dry-transaction#54]
Is it possible to compose transactions?

So as for a step instead of adding an operation I should add a transaction, in theory it should be possible but I have some problems using the container as step definitions are executed before all transactions are registered.

**Comment by AMHOL** [comment]
@alexandru-calinoiu yep, this is possible http://www.rubydoc.info/github/dry-rb/dry-transaction/Dry/Transaction/Sequence#append-instance_method

:smile:

**Comment by alexandru-calinoiu** [comment]
Love the work you guys are doing on this, keep it up!
