### ISSUE TITLE
When using step notifications, the *_success methods have no access to step arguments

### ISSUE THREAD

**Issue by rickenharp** [dry-rb/dry-transaction#55]
I was trying to implement logging through step notifications, and I notices that the *_success handlers only receive the output of the step.
In my case, the input to the step is a filename, which I wanted to log on success as well.
Would it make sense to have the success and failure steps have the same API of `(*args, value)`?

**Comment by mihairadulescu** [comment]
maybe you can pass that in output of that step as well..

**Comment by timriley** [comment]
@rickenharp thinking this through, I wonder if you do have all the information you need to log, but just in different places: if you want to log the input of a step, wouldn't that be the output of the previous step, and get logged there?

**Comment by timriley** [comment]
Ah, though I realise that some step arguments are sent externally, not just via the output of the previous step.

Yep, I think we should adjust how we broadcast notifications to include arguments. I'll probably do this after the work on #58, though, since it's our focus right now and will result in a fairly big restructure. I hope this is OK with you!

**Comment by rickenharp** [comment]
Class-based transactions look like a **really** great change, that would be a great boon for testing in our app, so that is very OK with me :)

**Comment by mihairadulescu** [comment]
@timriley nice ! .. thanks for your review!. having transaction progress callback would be really nice.

**Comment by GustavoCaso** [comment]
Hi, @rickenharp is been a long time, but we have completed the class-based transaction, and replace our pub/sub system with [dry-events](https://github.com/dry-rb/dry-events) and we currently send `step_name`, `args` and `value` for `succeeded` and `failed` events. Thanks for opening the issue ❤️
