### ISSUE TITLE
Add opt-in module for wrapping all steps in ROM database transaction

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-transaction#66]
This'd override the `#call` method of the transaction class, and call `super` from within a ROM transaction block.

Something like this would make it nice and easy for people to ensure DB integrity across their various steps.

**Comment by GustavoCaso** [comment]
@timriley is not this issue related with what @flash-gordon has implemented regarding `around` step?

**Comment by timriley** [comment]
@GustavoCaso you're right, `around` steps cover this and in any case, I think an out-of-the-box integration with rom isn't the right idea for a lib like dry-transaction either.
