### ISSUE TITLE
Additional arguments when reusing operations in steps

### ISSUE THREAD

**Issue by pashagray** [dry-rb/dry-transaction#76]
I wondering about providing additional arguments to steps. For example I have validate operation, which demands not only for input data, but also demands for some validator class.
For example:
```ruby
class CreateUser
  include Dry::Transaction
  include Dry::Transaction(container: Container)

  step :validate, with: 'operations.validate', args: { validator: UserForm }
  step :persist, with: 'operations.persist'
end


class Validate
  include Dry::Transaction::Operation

  def call(input)
    if input[:validator].new.validate(input[:params])
      Right(input)
    else
      Left(:not_valid)
    end
  end
end

transaction = CreateUser.new
result = transaction.call({ params: user_params })
```
While reading source code I see that such DSL (`args: { validator: UserForm } }`) is provided for passing `options`, but they are not accessible in `call` method.

Is it a good idea to implement such functionality?

At this moment I have to provide validator explicitly with #call:
```ruby
transaction = CreateUser.new
result = transaction.call({ params: user_params, validator: UserForm })
```

**Comment by GustavoCaso** [comment]
Hi @PavelTkachenko.

Your example above is interesting
> step :validate, with: 'operations.validate', args: { validator: UserForm }

So far we have a method but is missing documentation on the official website. `step_with_args` https://github.com/dry-rb/dry-transaction/blob/master/lib/dry/transaction/instance_methods.rb#L56

You can pass additional arguments to step operations using `#with_step_args`. Provide the operations as keys, and the arguments as an array. The arguments array will be **splatted**, So your operations must have a call method that allows passing extra arguments `#call(input, *args)`

I have written an example for you using it `step_with_args`
```ruby
class Container
  extend Dry::Container::Mixin

  register 'operations.validate',  -> input, validator {
    if validator.new.validate(input)
      Dry::Monads.Right(input)
    else
      Dry::Monads.Left(:not_valid)
    end
  }
end

class Validator
  def validate(input)
    true
  end
end

class CreateUser
  include Dry::Transaction(container: Container)

  step :validate, with: 'operations.validate'
end


CreateUser.new.with_step_args(
  validate: [Validator],
).call('hello') #=> Right('hello')
```

Hope this helps

**Comment by pashagray** [comment]
Hello @GustavoCaso!
This approach still requires to pass arguments outside of transaction. There is no way to provide additional arguments to steps within a transaction. I'll create a pull request to show this case in details.

**Comment by GustavoCaso** [comment]
@PavelTkachenko 
Yes, there is no way to pass arguments from the Transaction. So far we have the one I show you.
I think your solution could work. @timriley what do you think?

**Comment by timriley** [comment]
Hi @PavelTkachenko, now we have class-based transactions, there actually is a way to provide additional step args from within the transaction class, e.g.

```ruby
class MyTransaction
  step :one
  step :two

  def call(input)
    with_step_args(one: [validator: MySchema]).(input)
  end
end
```

And also, we can now _wrap_ individual operations in instance methods, which is another opportunity for intercepting the operation and providing default args:

```ruby
class MyTransaction
  step :one
  step :two

  def one(input)
    super(input, validator: MySchema)
  end
end
```

Would either of those work for you?

I can see the benefit of specifying default arguments right there in the step definition, but I just want to be careful before bulking up the step API with too many options. What're your thoughts on these alternative approaches I've shared with you here?

**Comment by pashagray** [comment]
@timriley, I faced a problem while extracting steps to operations. With my commit I refactored code to be like this:
```ruby
class UpdateUser
  include Dry::Transaction
  include Dry::Transaction(container: Containers::RecordOperations)

  step :find, with: 'ops.find', call_args: [User]
  step :validate, with: 'ops.validate', call_args: [User, UserForm]
  step :persist, with: 'ops.persist'
end
```

But I think that your second proposal with using `super` is good enough. Maybe it will be more code in class, but it looks pretty good. I think that you can reject pull request. Thanks for your feedbacks!

**Comment by AMHOL** [comment]
You could also do something like this, if you don't mind your steps not being resolved from the container.

```ruby
module OperationWrappers
  class Validator
    attr_reader :_validator

    def self.[](validator)
      new(validator.new)
    end

    def initialize(validator)
      @_validator = validator
    end

    def call(input)
      if _validator.validate(input)
        Dry::Monads.Right(input)
      else
        Dry::Monads.Left(:not_valid)
      end
    end
  end
end

class FiftyFiftyValidator
  def validate(input)
    [true, false].sample
  end
end

class CreateUser
  include Dry::Transaction(container: Container)

  step :validate, with: OperationWrappers::Validator[FiftyFiftyValidator]
  step :persist, with: 'operations.persist'
end
```

(not tested)

**Comment by quaternion** [comment]
This can be implemented through custom step adapters:
```ruby
class CustomStepAdapters
  extend Dry::Container::Mixin

  register :step, -> (step, *args, input) {
    # changes call args to hash and pass a step options
    step.call_operation(input: input, step_options: step.options)
  }
end

class FindModelOperation
  include Dry::Transaction::Operation
  
  # changed call arguments
  def call(input:, step_options:)
    model_class = step_options.fetch(:class) # fetch class option
    model = model_class.find_by(id: input[:id])
    if model
      input[:model] = model
      Right.new(input)
    else
      Left.new(:not_found)
    end
  end
end

class OperationsContainer
  extend Dry::Container::Mixin

  register :find_model, FindModelOperation.new
end

class UpdateUser
  include Dry::Transaction(container: OperationsContainer, step_adapters: CustomStepAdapters)

  step :find_model, class: User
end
```

Another option is change call args to `step.call_operation(input, step.options)`, but this generates dry-transaction exception  `ArgumentError: not enough arguments supplied for step +my_step+` for embedded operations.
