### ISSUE TITLE
Result matching API changed

### ISSUE THREAD

**Issue by kwando** [dry-rb/dry-transaction#8]
Commit face0888b385af571d50a9bf8aa2f25be4be2c6a changed the result matching API, this is not mentioned in the CHANGE log and the example in the README (in this section https://github.com/icelab/call_sheet#calling-a-transaction) is not valid anymore.

**Comment by timriley** [comment]
Ah yes! Thanks for the prompt about this, @kwando. I'll update the README and CHANGELOG tomorrow.

**Comment by solnic** [comment]
Would be nice to finally find/write a good tool for maintaining code examples in docs which makes sure they actually run with latest version.

**Comment by bbozo** [comment]
Include code examples from the docs in tests? (with a helpful reminder "if you see a broken test here make sure to update docs too")

**Comment by timriley** [comment]
Closing this one now since the matching behaviour has stabilised, particularly with the introduction of the `Dry::Matcher` in 0.5.0.
