### ISSUE TITLE
Allow to re-map step names for subscribers

### ISSUE THREAD

**Issue by gottfrois** [dry-rb/dry-transaction#89]
Would be nice to include Wisper subscriber mapping changes https://github.com/krisleech/wisper#mapping-an-event-to-a-different-method

Motivation for me is that my transactions often include very generic step names as:

```ruby
step :normalize
step :validate
step :persist
```

So it would be nice to be able to do:

```ruby
transaction = Transaction.new
transaction.subscribe(UserSubscriber.new, on: :persist, with: :user_persisted_successfuly)
```

**Comment by GustavoCaso** [comment]
@gottfrois I think is a valid addition to the library. Currently, @timriley has a PR that restore the broadcast method to receive the same arguments. I think once this one is merge we could talk about implementing this feature

**Comment by GustavoCaso** [comment]
@gottfrois dry-transaction now use `dry-events` instead of `wisper` gem, currently that feature from wisper is not available if you want you could open an issue in [dry-events](https://github.com/dry-rb/dry-events/issues)

**Comment by GustavoCaso** [comment]
I will close this issue and if end up implemented in `dry-events` I will reopen it.

Thanks @gottfrois
