### ISSUE TITLE
Allow for Short-Circuiting on Step that Returns Success

### ISSUE THREAD

**Issue by nannery** [dry-rb/dry-transaction#96]
A `dry-transaction` only short-circuits when a step returns a `Failure`. I want it to be possible to short-circuit upon a step returning a  `Success`. I was not able to figure out a clean way to do this.

Besides being able to short-circuit upon a singular step resulting in a `Success`, another similar feature could be to have an option that makes *all* of the steps glued together with `or` instead of `bind`, but this wouldn't be as flexible as I would want.

__Current options:__
1. Custom step: I didn't find a way to short-circuit out of the list of steps since it is hard-coded to join steps with `#bind`
2. Return a `Failure` and have outside code deal with the (`Failure`) result know that it is actually a success
3. Handle the `Failure` with a matcher that changes the eventual output (see below)

```ruby
gem 'dry-transaction', '=0.11.1'
require 'dry-transaction'

class Tranx
  include ::Dry::Transaction

  step :one
  step :two
  step :three

  def call(input, &block)
    if block
      super
    else
      super(input) do |result|
        result.failure(:two) { |v| Success(v.to_s + ': failure') }
        result.success(:two) { |v| Success(v.to_s + ': success') }
      end
    end
  end

  private

  def one(*)
    Success(1)
  end

  def two(*)
    Failure(2)
  end

  def three(*)
    Success(3)
  end
end

Tranx.new.call('foo') # => Success('2: failure')
```

**Comment by timriley** [comment]
Thanks for the note, @nannery. I'm not sure if this kind of behaviour really fits within the design of dry-transaction.

I can see 2 alternative options that could work well for you:

1. Create a plain class using dry-monads' "[do notation](http://dry-rb.org/gems/dry-monads/do-notation/)", which is still a very clean API  but one that gives you more control, allowing you to short-circuit with a simple early return, like regular old Ruby :)
2. Consider using something like [trailblazer-operation](http://trailblazer.to/2.1/trailblazer/wiring.html) or [trailblazer-activity](http://trailblazer.to/gems/activity/0.2/api.html), which provide much more sophisticated control flow APIs.

**Comment by nannery** [comment]
Awesome, those are great ideas. I hadn't seen the Do Notation when I wrote this, looks great!

**Comment by boof** [comment]
Another alternative I see here is to use an around step with catch and then throw from any step:

```ruby
catch(:exit) { block.call Success(input) } || Success(input)
```
